name: Generate Professional Materials

on:
  push:
    paths: 
      - 'data/*.json'
      - 'templates/*'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Create generated directory
      run: mkdir -p generated
    
    - name: Generate CV and LinkedIn content
      run: npm run generate
    
    - name: Commit generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add generated/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-update professional materials - $(date +'%Y-%m-%d %H:%M')"
          git push
        fi